### PR TITLE
Task/worker class/remove approve method

### PR DESCRIPTION
**Pull request by BeccaSheldon**
Probably should have created this branch from the readme branch but the approve method removal is in its own commit...@arvel let me know if you'd like a git redo. 

This PR is really just to remove the worker.approve method because it was only functional when we used mechanical turk. I also updated the readme to remove the approve method, which is why all the other readme changes are here too.

### CODE REVIEW

**Comment by syrnick** [comment]
That's where it's useful to open a pull request against the readme branch. That pull request would show only changes that are new here. The only gotcha is that the PR "remove approve -> Readme" should be merged before "Readme -> develop". (think about what happens otherwise ;)

**Comment by arvel** [comment]
OK... to keep it simple, let's just kill the readme branch.

**Comment by arvel** [comment]
+1

**Comment by BeccaSheldon** [comment]
@syrnick ahhh I know, I made it messy :( I'm going to delete the readme branch and just merge this one, which incorporates all the changes.

**Comment by ghost** [comment]
+1

**Pull request merged**
